#docker-compose.yaml
#version: '3.8'
services:
  modbus_app:
    build: .
    container_name: ampinvt
    restart: always
#    ports:
#      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # 单个日志文件最大为10MB
        max-file: "6"   # 最多保留3个日志文件
    network_mode: bridge
